static_address/config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get '/login' => 'sessions#new'

    resource :sessions, only: [:create, :destroy]
    resources :users
    resources :posts
    resources :comments

  resources :posts do
    member do
      get "upvote"

    end
  end

end

static_address/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

static_address/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, through: :user
	
	before_save { self.upvote = 0 if self.upvote == nil }
end

static_address/app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments, through: :posts
  has_secure_password
  validates :password_confirmation, presence: true
end

static_address/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

def current_user
  User.find(session[:user_id]) if session[:user_id]
end
	
	def logged_in_user
		unless logged_in?
			flash[:danger] = "Please log in."
			redirect_to login_url
		end
	end

	def logged_in?
		!current_user.nil?
	end
end

static_address/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.create(comment_params)
    @post = Post.find(params[:comment][:post_id])
    redirect_to post_path(@post)
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(Comment.params)
    redirect_to post_path(@comment)
  end

  def delete
    @comment = Comment.find(params[:id])
    @comment.delete
    redirect_to post_path
  end

  def show
    @comment = Comment.where({post_id: params[:id]})

  end

  private

  def comment_params
    params.require(:comment).permit(:content, :user_id, :post_id)
  end


end

static_address/app/controllers/login_controller.rb
class LoginController < ApplicationController

  def index
  end

end

static_address/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  layout 'application'
	before_action :logged_in_user, only: [:create, :destroy, :update]
	#before_action :authenticate

	def index

		if params[:user_id]
			@posts = Post.where({user_id: params[:user_id], avatar: params[:user_id]})
		else
			@posts = Post.all
		end
	end

	def show
		@post = Post.find(params[:id])
		@user = User.find(@post.user_id)
	end

	def create
		user = current_user || User.find(1)
		#fills in the user_id portion of the post_params which is needed.
		@post = user.posts.create(post_params)
		redirect_to '/posts/'+@post[:id].to_s
	end

	def new
		@post = Post.new
	end

  def upvote
    @post = Post.find(params[:id])
    @post.upvote = @post.upvote + 1
    @post.save
    redirect_to posts_path
  end

	private

	def post_params
		params.require(:post).permit(:title, :content, :youtubefile, :soundcloudfile, :user_id, :upvote, :artist, :genre, :media_selection)
	end

end

static_address/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		@user = User.new
	end

	def create
		user = User.find_by(name: params[:name])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to(posts_path)
		else
			flash[:error] = "Incorrect user Name or Password"
			redirect_to(login_path)
		end
	end

	def destroy
		# reset_session
		session[:user_id] = nil
		redirect_to(login_path)
	end
end

static_address/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
		@user = User.create(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to posts_path
		else
			render template: "sessions/new"
		end
	end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    puts params
    if @user.update_attributes user_params
      flash[:notice] = "You is succesfully updated"
      redirect_to user_path
    else
      flash[:error] = @user.errors.full_messages[0]
      redirect_to user_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :avatar)
  end
  end

static_address/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

static_address/app/helpers/application_helper.rb
module ApplicationHelper
end

static_address/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

static_address/app/views/layouts/_navigation.html.erb
<div class="sticky">

	<!--    NAVIGATION BAR   -->
	<nav class="top-bar" data-topbar role="navigation">
		<ul class="title-area">
			<li class="name">
				<a href="/posts" >static-address</a>
			</li>
			<li class="toggle-topbar menu-icon">
				<a href="#"><span>Menu</span></a>
			</li>
		</ul>
		<section class="top-bar-section">
			<!-- Left Nav Section -->
			<ul class="left">
				<li><a href="#">This Week</a></li>
				<li class="divider"></li>
				<li><a href="/posts/new">Submit New!</a></li>
			</ul>

			<!-- Right Nav Section -->
			<ul class="right">
				<li><a><%if session[:user_id] %>
        <%= link_to User.find(session[:user_id]).username, user_path(session[:user_id]) %>
        <% else%>
        <%= "signin"%>
        <%end%>

      </a></li>
				<li class="divider"></li>
				<li><a><%= link_to "Logout", sessions_path, method: :delete%></a></li>
			</ul>
		</section>
	</nav>
</div>

static_address/app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

static_address/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link href='https://fonts.googleapis.com/css?family=Quicksand' rel='stylesheet' type='text/css'>
    <title><%= content_for?(:title) ? yield(:title) : "Static Address" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Static Address" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
<!--		<script src="http://connect.soundcloud.com/sdk.js"></script>-->
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

		<%= javascript_include_tag('public') %>
    <%= csrf_meta_tags %>
	</head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

static_address/app/views/posts/index.html.erb
<div id="posts-wrapper">
	<h1>static-address</h1>
	<h3>Be heard through the static...</h3>

	<div id="posts-inner-wrapper">
		<% @posts.each do |post| %>
		<div id="posts-row" class="row post">
			<div id="upvote-wrapper" class="small-1 columns">
				<p><%= link_to "up", upvote_post_path(post)%></p>
				<p class="upvote-number"><%= post.upvote %></p>
			</div>
			<div class="small-9 columns">
				<h4 class="post-header-posts"><%= link_to post.title, post %></h4>
				</br>
				<p><%= post.content %></p>
			</div>
			<div class="small-2 columns">
				<p>By: <%= link_to post.user.username, user_path(post.user.id) %></p>
				<img src="<%= post.user.avatar %>" alt="user avatar">
			</div>
	</div>
				<% end %>

</div> <!-- closes container	-->

<footer>
	<p class="disclaimer">we do not own any of the rights to the music on our website</p>
	<p class="disclaimer">&copy; Raina Koren | Anthony Lui | Steve Edelmann | Matt Fewer</p>
</footer>

static_address/app/views/posts/new.html.erb
<%= form_for @post do |f| %>

<!-- hidden_field_tag(:user_id, session[:user_id]) #need to check this-->
<%= f.label :title, 'Song Title' %>
<%= f.text_field :title, placeholder: 'Song Title' %> <br>
<%= f.label :artist, 'Artist' %>
<%= f.text_field :artist, placeholder: 'Artist' %> <br>
<%= f.label :genre, 'Genre' %>
<%= f.text_field :genre, placeholder: 'Genre' %> <br>
<%= f.label :content, 'Body Content' %>
<%= f.text_area :content, placeholder: 'Enter your body content here!' %>

<%= f.label :soundfile, 'Soundcloud'%>
<%= f.radio_button(:media_selection, '1')%><br/>
<div id="soundcloud-input" class="hidden"><%= f.text_area :soundcloudfile, placeholder: 'Soundcloud Link' %></div>

<%= f.label :soundfile, 'YouTube'%>
<%= f.radio_button(:media_selection, '2')%>
<div id="youtube-input" class="hidden"><%= f.text_area :youtubefile, placeholder: 'YouTube Link' %></div><br/>
<%= f.submit %>

<% end %>

<script> 
	
	var mediaSelection = 0;
	$('#post_media_selection_1').on("click", function(){
		$('#soundcloud-input').toggle("show");
		$('#youtube-input').hide();
		mediaSelection = 1;
	});
	$('#post_media_selection_2').on("click", function(){
		$('#youtube-input').toggle("show");
		$('#soundcloud-input').hide();
		mediaSelection = 2;
	});
</script>

static_address/app/views/posts/show.html.erb
<script type="application/javascript">
	var mediaNum = "<%= raw(@post.media_selection) %>"
	console.log(mediaNum)
	
	var url = "<%= (@post.media_selection == "1")? @post.soundcloudfile : @post.youtubefile %>";
	console.log(url)
	
</script>

<div id="show-wrapper">
	<div class="row">
		<div id="title-row-show" class="small-6 small-centered columns">
			<h1><%= @post.title %></h1>
		</div>
	</div>

<div id="post-inner-wrapper">

	<div id="media-row" class="row">
		<div class="small-12 medium-6 columns">
			<h3 id="show-post-title">By: <%= @user.username %> </h3>
		</div>
		<div id="media-player-div" class="small-12 medium-6 columns">
			<div id="target"></div>
		</div>
	</div>

	<hr>

	<div class="row">
		<div class="small-6 small-centered columns">
			<h2>Body Title</h2>
		</div>
		
		<div class="small-12 columns">
			<section>
				<p><%= @post.content %></p>
			</section>
		</div>
	</div>
</div>
</div>
<div class="comments-wrapper">
	<div id="comment-inner-wrapper">
			<a data-dropdown="drop2" aria-controls="drop2" aria-expanded="false">Leave a comment</a>
			<% link_to "leave a comment", comments_path%>
			<div id="drop2" data-dropdown-content class="f-dropdown content" aria-hidden="true" tabindex="-1">
  			<%= form_for @comment do |f| %>
  			<%= f.label :content, 'What do you think?' %>
			<%= f.text_field :content, placeholder: 'Write your comments here...', :size => 150 %> <br>
			<%= f.hidden_field :user_id, :value => session[:username]%>
			<%= f.hidden_field :post_id, :value => @post.id%>
			<%= f.submit %>
			<%end%>
			</div>
	</div>
                <div class="row">
                    <div class="small-9 small-centered columns">
						<% @comments.each do |comment|%>        
                        <h6><%= comment.user_id %></h6>
                        <p><%= comment.content %></p>
        				<% end %>
                    </div>
                </div>    
            </div>

</div>

static_address/app/views/users/edit.html.erb
<br/>
<div class="row">
  <div class="small-4 small-centered large-4 large-centered columns">
    <%= form_for @user do |f| %>
      <%= f.label :name, "Name:" %>
      <%= f.text_field :name, placeholder: @user.name %><br>
      <%= f.label :username, "Username:" %>
      <%= f.text_field :username, placeholder: @user.username %><br>
      <%= f.label :password, "Password:" %>
      <%= f.password_field :password %><br>
      <%= f.label :password_confirmation, "Confirm Password:" %>
      <%= f.password_field :password_confirmation %><br>
      <%= f.label :email, "Email:" %>
      <%= f.text_field :email, placeholder: @user.email %><br>
      <%= f.label :avatar, "Avatar link:" %>
      <%= f.text_field :avatar, placeholder: @user.avatar %><br>
      <%= f.submit%>
    <%end%>

  </div>
</div>

static_address/app/views/users/show.html.erb
<h1>User Info Page</h1>
<div id="edit-container">
	<div class="row">
	 <div class="small-10 small-centered columns">
			<div class="inner-container-edit panel callout radius">
			<div class="row">
				<div class="small-6 columns">
					<h4>Username: </h4><p class="edit-bold"><%=@user.username%></p>
					<h4>Name: </h4><p><%=@user.name%></p>
				</div>
				<div class="profpic small-6 columns clearfix">
					<img id="user-avatar-img right" src="<%=@user.avatar%>"/>
				</div>	
			</div>
				<div id="edit-button-submit"><%= link_to 'Edit', edit_user_path(@user.id), class: 'button round' %></div>
		 </div>
		</div>
	</div>
</div>

static_address/app/views/welcome/index.html.erb
<html>

<head>
  <title>Welcome to Static-Address</title>
  <link rel="stylesheet" type="text/css" href="index.css">
</head>

<body>

  <div id="welcome_index_title">
    <h1>Static Address</h1>
    <h6>Be Heard Over the Static</h6>
  </div>
  <h3 id="current_ten">CURRENT TOP TEN</h3>
  <ul>

  </ul>
  <%= link_to "Posts", posts_path %></br>
  <%= link_to "Make a New Post", new_post_path %></br>
  <%= link_to "LOGIN", login_path %></br>
  <%= link_to "LOGOUT", sessions_path, method: :delete %>


</body>

</html>